name: Linting and Formatting
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  lint:
    name: Prettier and ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checks Out the Repository
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Sets up the Bun enviornment
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - name: Installing Bun Dependencies
        run: |
          bun install .
          bun install -D jest ts-jest @types/jest typescript
      - name: Linting The Code
        run: |
          bun eslint .
      - name: Checking for Formatting
        run: |
          bunx prettier . --check
      - name: Running Tests
        run: |
          npm test
